services:
  db:
    image: postgres:15-alpine
    container_name: bankapi_test_db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: bankapi_test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - api_network

volumes:
  postgres_data:

networks:
  api_network:
    driver: bridge
